version: '3.8'  # Specify Docker Compose version

services:
  postgres:
    image: postgres:16  # Use the image you built
    restart: always      # Restart the container if it stops
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=tour_registration
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # Map container's port 5432 to host's port 5432

  elasticsearch:
    image: elasticsearch:7.17.22
    restart: always
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.22
    restart: always
    volumes:
      - ./logstash_data:/usr/share/logstash/data
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./postgresql-42.6.2.jar:/usr/share/logstash/postgresql-42.6.2.jar
    depends_on:
      - elasticsearch  # Ensure Elasticsearch starts before Logstash
      - postgres      # Ensure PostgreSQL starts before Logstash
    environment:
      - xpack.monitoring.enabled=false  # Disable X-Pack monitoring if not needed
#      - XPACK_MONITORING_ENABLED=false # For Logstash 8.x and newer, use this instead
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
#docker build -t my-postgres . #
#docker run -d --name postgres-continer -p 5432:5432 my-postgres #
#docker exec -it postgres-container bash #

#psql -U user -d tour_registration #
#sudo docker run -d --name elasticsearch --net bridge -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.17.22
#sudo docker pull docker.elastic.co/logstash/logstash:7.17.22
#docker run -d --name my-logstash \
#    -v /path/to/your/logstash.conf:/usr/share/logstash/pipeline/logstash.conf \
#    docker.elastic.co/logstash/logstash:<version>

#INSERT INTO tour (id, created_date, description, end_date, name, price, start_date)
#VALUES (
#    gen_random_uuid(),
#    '2023-06-28',
#    'Tour description',
#    '2023-07-15',
#    'Trip to the mountains',
#    120000.50,
#    '2023-07-01'
#); -- tour example