FROM postgres:16

ENV POSTGRES_USER user
ENV POSTGRES_PASSWORD dbpassword
ENV POSTGRES_DB tour_registration

#docker build -t my-postgres . #
#docker run -d --name postgres-continer -p 5432:5432 my-postgres #
#docker exec -it postgres-container bash #
#psql -U user -d tour_registration #
