openapi: 3.0.3
info:
  title: Tour Registration
  description: API for managing tours
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/tour'  # Replace with your base URL

paths:
  /tourCrud:
    post:
      summary: Create a new tour
      description: Creates a new tour based on the provided data.
      operationId: postTour
      requestBody:
        description: New tour data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TourDto'
      responses:
        '201':
          description: Tour successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TourDto'
          headers:
            Location:
              description: URI of the created tour
              schema:
                type: string

  /tourCrud/{tourId}:
    put:
      summary: Update tour
      description: Updates tour information by its ID.
      operationId: putTourById
      parameters:
        - name: tourId
          in: path
          description: Tour ID
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Updated tour data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TourDto'
      responses:
        '200':
          description: Tour successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TourDto'
        '404':
          description: Tour not found
    patch:
      summary: Partially update tour
      description: Partially updates tour information by its ID.
      operationId: patchTourById
      parameters:
        - name: tourId
          in: path
          description: Tour ID
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Partially updated tour data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TourDto'
      responses:
        '200':
          description: Tour successfully partially updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TourDto'
        '404':
          description: Tour not found
    delete:
      summary: Delete tour
      description: Deletes a tour by its ID.
      operationId: deleteTourById
      parameters:
        - name: tourId
          in: path
          description: Tour ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Tour successfully deleted
        '404':
          description: Tour not found

components:
  schemas:
    TourDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Tour ID
        name:
          type: string
          description: Tour name
        description:
          type: string
          description: Tour description
        price:
          type: number
          description: Tour price
        startDate:
          type: string
          format: date
          description: Tour start date
        endDate:
          type: string
          format: date
          description: Tour end date
      required:
        - name
        - priceS