openapi: 3.0.3
info:
  title: Tour Registration
  description: API for managing tours
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/tours'  # Replace with your base URL

paths:
  /tours:
    get:
      summary: Get list of tours
      description: Returns a list of all tours with pagination support.
      parameters:
        - name: page
          in: query
          description: Page number (starting from 0)
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Page size
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Successful response with an array of tours
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tour'
    post:
      summary: Create a new tour
      description: Creates a new tour based on the provided data.
      requestBody:
        description: New tour data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tour'
      responses:
        '201':
          description: Tour successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tour'

  /tours/{tourId}:
    get:
      summary: Get tour by ID
      description: Returns information about a tour by its ID.
      parameters:
        - name: tourId
          in: path
          description: Tour ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response with tour data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tour'
        '404':
          description: Tour not found
    put:
      summary: Update tour
      description: Updates tour information by its ID.
      parameters:
        - name: tourId
          in: path
          description: Tour ID
          required: true
          schema:
            type: integer
      requestBody:
        description: Updated tour data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tour'
      responses:
        '200':
          description: Tour successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tour'
        '404':
          description: Tour not found
    delete:
      summary: Delete tour
      description: Deletes a tour by its ID.
      parameters:
        - name: tourId
          in: path
          description: Tour ID
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Tour successfully deleted
        '404':
          description: Tour not found

components:
  schemas:
    Tour:
      type: object
      properties:
        id:
          type: integer
          description: Tour ID
        name:
          type: string
          description: Tour name
        description:
          type: string
          description: Tour description
        price:
          type: number
          description: Tour price
        startDate:
          type: string
          format: date
          description: Tour start date
        endDate:
          type: string
          format: date
          description: Tour end date
      required:
        - name
        - price
