openapi: 3.0.3
info:
  title: Tour Registration
  description: API for managing tours
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/tour'  # Replace with your base URL


paths:
  /tourCrud:
    post:
      summary: Create a new tour
      description: Creates a new tour based on the provided data.
      operationId: postTour
      security:
        - OAuth2Bearer: []
      requestBody:
        description: New tour data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TourDto'
      responses:
        '201':
          description: Tour successfully created
          headers:
            Location:
              description: URI of the created tour
              schema:
                type: string

  /tourCrud/{tourId}:
    put:
      summary: Update tour
      description: Updates tour information by its ID.
      operationId: putTourById
      security:
        - OAuth2Bearer: [ ]
      parameters:
        - name: tourId
          in: path
          description: Tour ID
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Updated tour data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TourDto'
      responses:
        '200':
          description: Tour successfully updated
        '401':
          description: Unauthorized access  
        '404':
          description: Tour not found
    patch:
      summary: Partially update tour
      description: Partially updates tour information by its ID.
      operationId: patchTourById
      security:
        - OAuth2Bearer: [ ]
      parameters:
        - name: tourId
          in: path
          description: Tour ID
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Partially updated tour data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TourDto'
      responses:
        '200':
          description: Tour successfully partially updated
        '401':
          description: Unauthorized access  
        '404':
          description: Tour not found
    delete:
      summary: Delete tour
      description: Deletes a tour by its ID.
      operationId: deleteTourById
      security:
        - OAuth2Bearer: [ ]
      parameters:
        - name: tourId
          in: path
          description: Tour ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Tour successfully deleted
        '401':
          description: Unauthorized access
        '404':
          description: Tour not found
components:
  securitySchemes:
    OAuth2Bearer:
      type: http
      scheme: bearer
      bearerFormat: opaque

  schemas:
    TourDto:
      type: object
      properties:
        name:
          type: string
          description: Tour name
          minLength: 1
          maxLength: 100
        description:
          type: string
          description: Tour description
          minLength: 1
          maxLength: 1000
        price:
          type: number
          format: double
          description: Tour price
          minimum: 0
        startDate:
          type: string
          format: date
          description: Tour start date
        endDate:
          type: string
          format: date
          description: Tour end date
      required:
        - name
        - description
        - price
        - startDate
        - endDate